# -*- coding: utf-8 -*-
"""QR Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11j9xUjzkmDquJ3Gwchfd5w01rJzQGCGn
"""

!pip install qrcode[pil] Pillow matplotlib

import qrcode
import matplotlib.pyplot as plt
from PIL import Image

# Data to encode
data = "https://google.com"

# Generate QR code
qr = qrcode.QRCode(
    version=1,
    error_correction=qrcode.constants.ERROR_CORRECT_L,
    box_size=10,
    border=4,
)
qr.add_data(data)
qr.make(fit=True)

# Create an image from the QR code instance
img = qr.make_image(fill="black", back_color="white")

# Save the image to a file
img.save("qr_code.png")

# Display the image in Colab using matplotlib
img = Image.open("qr_code.png")
plt.imshow(img)
plt.axis('off')  # No axis for a cleaner look
plt.show()